### PR TITLE
fix(eslint-config): override max lines for certain files

### LINKED ISSUE #58: Disable max-lines for certain files
As discussed internally, we want to disable the `max-lines` rule for the following named files;

* `types.ts`
* `*.types.ts`
* `machine.{ts,tsx,js,jsx,mjs,cjs}`
* `*.machine.{ts,tsx,js,jsx,mjs,cjs}`

### PR DESCRIPTION
**Pull request by daniellizik**
fixes #58

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @tablecheck/eslint-config@1.7.2-canary.60.2317081826.0
  npm install @tablecheck/scripts@1.12.2-canary.60.2317081826.0
  # or 
  yarn add @tablecheck/eslint-config@1.7.2-canary.60.2317081826.0
  yarn add @tablecheck/scripts@1.12.2-canary.60.2317081826.0
  ```
</details>

### CODE REVIEW

File: packages/eslint-config/overrides/maxLines.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+module.exports = {
+  files: [
+    '**/types.ts',
+    '**/*.types.ts',
+    '**/machine.{ts,tsx,js,jsx,mjs,cjs}',
+    '**/*.machine.{ts,tsx,js,jsx,mjs,cjs}'
+  ],
+  rules: {
+    'max-lines': 'off'
```
Comment (daniellizik) [inline packages/eslint-config/overrides/maxLines.js:9]: `npm run lint` passes in another project when i add this directly to the scripts in node modules

**Review by SimeonC — APPROVED** [review]

**Review by wahidfarid — APPROVED** [review]
